name: Build and Deploy
on:
  push:	
    branches:	
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: grasilife/github-pages-deploy-action@master
      env:
        BASE_BRANCH: main # The branch the action should deploy from.
        BUILD_SCRIPT: yarn install && yarn run-script docs:build # The build script the action should run prior to deploying.
